# Generated by Django 5.1.4 on 2025-01-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='short_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
