# Generated by Django 5.1.4 on 2025-04-10 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_video_short_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=5, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BussinessContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.author'),
        ),
        migrations.AddField(
            model_name='author',
            name='contact',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.bussinesscontact'),
        ),
    ]
